import type { DefaultCategorySlug } from "@/server/catalog/default-categories";
import type { Unit } from "@/lib/units";

/**
 * One entry in the built-in справочник частых продуктов (VISION §3.1):
 * a familiar product the cart's autocomplete (task 1.3) can offer for free,
 * instantly, without an AI call. Household catalogs are seeded/matched from
 * this list; anything not here falls back to the AI icon/department picker.
 */
export interface ReferenceProduct {
  /** RU, capitalized as a product label, e.g. "Помидоры". */
  readonly name: string;
  /** A single emoji. */
  readonly icon: string;
  readonly categorySlug: DefaultCategorySlug;
  /** Sensible default purchase unit. */
  readonly unit: Unit;
  /** Lowercase search aliases (plural/singular, colloquial, common misspelling). May be empty. */
  readonly aliases: readonly string[];
}

/**
 * ~180 realistic Russian household staples across all 7 departments
 * (task 1.2). Produce and grocery (бакалея — dry goods, canned goods,
 * spices, sweets, drinks) are the largest, matching a real household's
 * shopping list. Every product named in DESIGN_BRIEF §5's example content
 * is present so those screens render against real catalog rows rather than
 * mock strings.
 */
export const REFERENCE_PRODUCTS: readonly ReferenceProduct[] = [
  // --- Овощи и фрукты (produce) ---
  {
    name: "Помидоры",
    icon: "🍅",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["помидор", "томат", "томаты"],
  },
  {
    name: "Помидоры черри",
    icon: "🍅",
    categorySlug: "produce",
    unit: "уп",
    aliases: ["черри", "помидоры чери"],
  },
  {
    name: "Огурцы",
    icon: "🥒",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["огурец"],
  },
  {
    name: "Лимоны",
    icon: "🍋",
    categorySlug: "produce",
    unit: "шт",
    aliases: ["лимон"],
  },
  {
    name: "Авокадо",
    icon: "🥑",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Чеснок",
    icon: "🧄",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Лук",
    icon: "🧅",
    categorySlug: "produce",
    unit: "шт",
    aliases: ["лук репчатый"],
  },
  {
    name: "Зелёный лук",
    icon: "🧅",
    categorySlug: "produce",
    unit: "пучок",
    aliases: ["лук зеленый"],
  },
  {
    name: "Морковь",
    icon: "🥕",
    categorySlug: "produce",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Перец болгарский",
    icon: "🫑",
    categorySlug: "produce",
    unit: "шт",
    aliases: ["перец сладкий"],
  },
  {
    name: "Перец чили",
    icon: "🌶️",
    categorySlug: "produce",
    unit: "шт",
    aliases: ["чили", "острый перец"],
  },
  {
    name: "Картофель",
    icon: "🥔",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["картошка"],
  },
  {
    name: "Капуста белокочанная",
    icon: "🥬",
    categorySlug: "produce",
    unit: "шт",
    aliases: ["капуста"],
  },
  {
    name: "Капуста цветная",
    icon: "🥦",
    categorySlug: "produce",
    unit: "шт",
    aliases: ["цветная капуста"],
  },
  {
    name: "Брокколи",
    icon: "🥦",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Кабачки",
    icon: "🥒",
    categorySlug: "produce",
    unit: "шт",
    aliases: ["кабачок", "цукини"],
  },
  {
    name: "Баклажаны",
    icon: "🍆",
    categorySlug: "produce",
    unit: "шт",
    aliases: ["баклажан", "синенькие"],
  },
  {
    name: "Свёкла",
    icon: "🍠",
    categorySlug: "produce",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Редис",
    icon: "🌱",
    categorySlug: "produce",
    unit: "пучок",
    aliases: [],
  },
  {
    name: "Шпинат",
    icon: "🥬",
    categorySlug: "produce",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Салат листовой",
    icon: "🥬",
    categorySlug: "produce",
    unit: "шт",
    aliases: ["салат"],
  },
  {
    name: "Укроп",
    icon: "🌿",
    categorySlug: "produce",
    unit: "пучок",
    aliases: [],
  },
  {
    name: "Петрушка",
    icon: "🌿",
    categorySlug: "produce",
    unit: "пучок",
    aliases: [],
  },
  {
    name: "Кинза",
    icon: "🌿",
    categorySlug: "produce",
    unit: "пучок",
    aliases: ["кориандр"],
  },
  {
    name: "Базилик",
    icon: "🌿",
    categorySlug: "produce",
    unit: "пучок",
    aliases: [],
  },
  {
    name: "Мята",
    icon: "🌿",
    categorySlug: "produce",
    unit: "пучок",
    aliases: [],
  },
  {
    name: "Имбирь",
    icon: "🫚",
    categorySlug: "produce",
    unit: "г",
    aliases: [],
  },
  {
    name: "Сельдерей",
    icon: "🥬",
    categorySlug: "produce",
    unit: "пучок",
    aliases: [],
  },
  {
    name: "Спаржа",
    icon: "🥬",
    categorySlug: "produce",
    unit: "пучок",
    aliases: [],
  },
  {
    name: "Грибы шампиньоны",
    icon: "🍄",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["шампиньоны", "грибы"],
  },
  {
    name: "Яблоки",
    icon: "🍎",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["яблоко"],
  },
  {
    name: "Бананы",
    icon: "🍌",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["банан"],
  },
  {
    name: "Апельсины",
    icon: "🍊",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["апельсин"],
  },
  {
    name: "Мандарины",
    icon: "🍊",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["мандарин"],
  },
  {
    name: "Груши",
    icon: "🍐",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["груша"],
  },
  {
    name: "Виноград",
    icon: "🍇",
    categorySlug: "produce",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Клубника",
    icon: "🍓",
    categorySlug: "produce",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Малина",
    icon: "🍓",
    categorySlug: "produce",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Черника",
    icon: "🫐",
    categorySlug: "produce",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Персики",
    icon: "🍑",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["персик"],
  },
  {
    name: "Сливы",
    icon: "🍑",
    categorySlug: "produce",
    unit: "кг",
    aliases: ["слива"],
  },
  {
    name: "Арбуз",
    icon: "🍉",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Дыня",
    icon: "🍈",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Киви",
    icon: "🥝",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Манго",
    icon: "🥭",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Ананас",
    icon: "🍍",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Грейпфрут",
    icon: "🍊",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Лайм",
    icon: "🍋",
    categorySlug: "produce",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Тыква",
    icon: "🎃",
    categorySlug: "produce",
    unit: "кг",
    aliases: [],
  },

  // --- Молочное и яйца (dairy) ---
  { name: "Молоко", icon: "🥛", categorySlug: "dairy", unit: "л", aliases: [] },
  {
    name: "Молоко безлактозное",
    icon: "🥛",
    categorySlug: "dairy",
    unit: "л",
    aliases: ["безлактозное молоко"],
  },
  {
    name: "Молоко овсяное",
    icon: "🥛",
    categorySlug: "dairy",
    unit: "л",
    aliases: ["овсяное молоко"],
  },
  {
    name: "Молоко миндальное",
    icon: "🥛",
    categorySlug: "dairy",
    unit: "л",
    aliases: ["миндальное молоко"],
  },
  {
    name: "Сливки",
    icon: "🥛",
    categorySlug: "dairy",
    unit: "мл",
    aliases: [],
  },
  {
    name: "Взбитые сливки",
    icon: "🥛",
    categorySlug: "dairy",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Сметана",
    icon: "🥣",
    categorySlug: "dairy",
    unit: "г",
    aliases: [],
  },
  { name: "Кефир", icon: "🥛", categorySlug: "dairy", unit: "л", aliases: [] },
  {
    name: "Ряженка",
    icon: "🥛",
    categorySlug: "dairy",
    unit: "л",
    aliases: [],
  },
  {
    name: "Простокваша",
    icon: "🥛",
    categorySlug: "dairy",
    unit: "л",
    aliases: [],
  },
  { name: "Айран", icon: "🥛", categorySlug: "dairy", unit: "л", aliases: [] },
  {
    name: "Йогурт",
    icon: "🥛",
    categorySlug: "dairy",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Йогурт питьевой",
    icon: "🥛",
    categorySlug: "dairy",
    unit: "л",
    aliases: [],
  },
  { name: "Творог", icon: "🧀", categorySlug: "dairy", unit: "г", aliases: [] },
  {
    name: "Творожный сыр",
    icon: "🧀",
    categorySlug: "dairy",
    unit: "г",
    aliases: ["сливочный сыр", "филадельфия"],
  },
  {
    name: "Масло сливочное",
    icon: "🧈",
    categorySlug: "dairy",
    unit: "г",
    aliases: ["сливочное масло"],
  },
  {
    name: "Маргарин",
    icon: "🧈",
    categorySlug: "dairy",
    unit: "г",
    aliases: [],
  },
  {
    name: "Яйца",
    icon: "🥚",
    categorySlug: "dairy",
    unit: "шт",
    aliases: ["яйцо"],
  },
  {
    name: "Сыр твёрдый",
    icon: "🧀",
    categorySlug: "dairy",
    unit: "г",
    aliases: ["сыр"],
  },
  {
    name: "Сыр плавленый",
    icon: "🧀",
    categorySlug: "dairy",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Пармезан",
    icon: "🧀",
    categorySlug: "dairy",
    unit: "г",
    aliases: [],
  },
  {
    name: "Моцарелла",
    icon: "🧀",
    categorySlug: "dairy",
    unit: "г",
    aliases: [],
  },
  { name: "Фета", icon: "🧀", categorySlug: "dairy", unit: "г", aliases: [] },
  {
    name: "Сгущённое молоко",
    icon: "🥫",
    categorySlug: "dairy",
    unit: "банка",
    aliases: ["сгущенка"],
  },

  // --- Мясо и курица (meat) ---
  {
    name: "Куриное филе",
    icon: "🍗",
    categorySlug: "meat",
    unit: "кг",
    aliases: ["куриная грудка"],
  },
  {
    name: "Куриные бёдра",
    icon: "🍗",
    categorySlug: "meat",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Куриные крылышки",
    icon: "🍗",
    categorySlug: "meat",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Курица целая",
    icon: "🍗",
    categorySlug: "meat",
    unit: "шт",
    aliases: ["курица"],
  },
  {
    name: "Фарш говяжий",
    icon: "🥩",
    categorySlug: "meat",
    unit: "кг",
    aliases: ["говяжий фарш"],
  },
  {
    name: "Фарш свиной",
    icon: "🥩",
    categorySlug: "meat",
    unit: "кг",
    aliases: ["свиной фарш"],
  },
  {
    name: "Фарш смешанный",
    icon: "🥩",
    categorySlug: "meat",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Говядина",
    icon: "🥩",
    categorySlug: "meat",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Свинина",
    icon: "🥩",
    categorySlug: "meat",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Баранина",
    icon: "🥩",
    categorySlug: "meat",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Индейка филе",
    icon: "🦃",
    categorySlug: "meat",
    unit: "кг",
    aliases: ["филе индейки"],
  },
  { name: "Бекон", icon: "🥓", categorySlug: "meat", unit: "г", aliases: [] },
  {
    name: "Сосиски",
    icon: "🌭",
    categorySlug: "meat",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Колбаса варёная",
    icon: "🌭",
    categorySlug: "meat",
    unit: "г",
    aliases: ["колбаса"],
  },
  {
    name: "Колбаса копчёная",
    icon: "🌭",
    categorySlug: "meat",
    unit: "г",
    aliases: [],
  },
  { name: "Ветчина", icon: "🍖", categorySlug: "meat", unit: "г", aliases: [] },
  {
    name: "Лосось",
    icon: "🐟",
    categorySlug: "meat",
    unit: "кг",
    aliases: ["семга"],
  },
  {
    name: "Креветки",
    icon: "🍤",
    categorySlug: "meat",
    unit: "кг",
    aliases: [],
  },

  // --- Хлеб и выпечка (bakery) ---
  {
    name: "Хлеб белый",
    icon: "🍞",
    categorySlug: "bakery",
    unit: "шт",
    aliases: ["белый хлеб", "батон"],
  },
  {
    name: "Хлеб чёрный",
    icon: "🍞",
    categorySlug: "bakery",
    unit: "шт",
    aliases: ["черный хлеб", "ржаной хлеб"],
  },
  {
    name: "Багет",
    icon: "🥖",
    categorySlug: "bakery",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Лаваш",
    icon: "🫓",
    categorySlug: "bakery",
    unit: "шт",
    aliases: [],
  },
  { name: "Пита", icon: "🫓", categorySlug: "bakery", unit: "шт", aliases: [] },
  {
    name: "Булочки для бургеров",
    icon: "🍞",
    categorySlug: "bakery",
    unit: "уп",
    aliases: ["булки для бургеров"],
  },
  {
    name: "Круассаны",
    icon: "🥐",
    categorySlug: "bakery",
    unit: "уп",
    aliases: ["круассан"],
  },
  {
    name: "Тортилья",
    icon: "🫓",
    categorySlug: "bakery",
    unit: "уп",
    aliases: ["лепешки"],
  },
  {
    name: "Хлебцы",
    icon: "🍘",
    categorySlug: "bakery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Сухари панировочные",
    icon: "🍞",
    categorySlug: "bakery",
    unit: "уп",
    aliases: ["панировочные сухари"],
  },
  {
    name: "Слоёное тесто",
    icon: "🥐",
    categorySlug: "bakery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Дрожжевое тесто",
    icon: "🥐",
    categorySlug: "bakery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Печенье",
    icon: "🍪",
    categorySlug: "bakery",
    unit: "уп",
    aliases: [],
  },
  { name: "Кекс", icon: "🧁", categorySlug: "bakery", unit: "шт", aliases: [] },

  // --- Бакалея (grocery) ---
  {
    name: "Мука",
    icon: "🌾",
    categorySlug: "grocery",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Сахар белый",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "кг",
    aliases: ["сахар"],
  },
  {
    name: "Сахар коричневый",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "кг",
    aliases: ["тростниковый сахар"],
  },
  {
    name: "Соль",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Разрыхлитель",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["разрыхлитель теста", "пекарский порошок"],
  },
  {
    name: "Сода пищевая",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["сода"],
  },
  {
    name: "Ванилин",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Ванильный сахар",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Кукурузный крахмал",
    icon: "🌽",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["крахмал"],
  },
  { name: "Рис", icon: "🍚", categorySlug: "grocery", unit: "кг", aliases: [] },
  {
    name: "Гречка",
    icon: "🌾",
    categorySlug: "grocery",
    unit: "кг",
    aliases: ["гречневая крупа"],
  },
  {
    name: "Овсяные хлопья",
    icon: "🌾",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["овсянка", "геркулес"],
  },
  {
    name: "Манная крупа",
    icon: "🌾",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["манка"],
  },
  {
    name: "Булгур",
    icon: "🌾",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Кускус",
    icon: "🌾",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Киноа",
    icon: "🌾",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Паста",
    icon: "🍝",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["макароны"],
  },
  {
    name: "Листы лазаньи",
    icon: "🍝",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["лазанья листы"],
  },
  {
    name: "Спагетти",
    icon: "🍝",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Масло оливковое",
    icon: "🫒",
    categorySlug: "grocery",
    unit: "мл",
    aliases: [],
  },
  {
    name: "Масло подсолнечное",
    icon: "🌻",
    categorySlug: "grocery",
    unit: "л",
    aliases: ["растительное масло"],
  },
  {
    name: "Уксус",
    icon: "🧴",
    categorySlug: "grocery",
    unit: "мл",
    aliases: [],
  },
  {
    name: "Уксус бальзамический",
    icon: "🧴",
    categorySlug: "grocery",
    unit: "мл",
    aliases: ["бальзамик"],
  },
  {
    name: "Соевый соус",
    icon: "🧴",
    categorySlug: "grocery",
    unit: "мл",
    aliases: [],
  },
  {
    name: "Томатная паста",
    icon: "🥫",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Томаты в собственном соку",
    icon: "🥫",
    categorySlug: "grocery",
    unit: "банка",
    aliases: [],
  },
  {
    name: "Кетчуп",
    icon: "🍅",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Майонез",
    icon: "🥫",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Горчица",
    icon: "🥫",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Кокосовое молоко",
    icon: "🥥",
    categorySlug: "grocery",
    unit: "банка",
    aliases: [],
  },
  {
    name: "Кукуруза консервированная",
    icon: "🌽",
    categorySlug: "grocery",
    unit: "банка",
    aliases: [],
  },
  {
    name: "Фасоль консервированная",
    icon: "🥫",
    categorySlug: "grocery",
    unit: "банка",
    aliases: [],
  },
  {
    name: "Горошек консервированный",
    icon: "🥫",
    categorySlug: "grocery",
    unit: "банка",
    aliases: ["зеленый горошек"],
  },
  {
    name: "Оливки",
    icon: "🫒",
    categorySlug: "grocery",
    unit: "банка",
    aliases: [],
  },
  {
    name: "Маслины",
    icon: "🫒",
    categorySlug: "grocery",
    unit: "банка",
    aliases: [],
  },
  {
    name: "Тунец консервированный",
    icon: "🥫",
    categorySlug: "grocery",
    unit: "банка",
    aliases: ["тунец"],
  },
  {
    name: "Чечевица",
    icon: "🌾",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Фасоль сухая",
    icon: "🌾",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  { name: "Нут", icon: "🌾", categorySlug: "grocery", unit: "уп", aliases: [] },
  {
    name: "Кофе",
    icon: "☕",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Чай чёрный",
    icon: "🍵",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["чай"],
  },
  {
    name: "Чай зелёный",
    icon: "🍵",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Какао порошок",
    icon: "🍫",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["какао"],
  },
  {
    name: "Шоколад тёмный",
    icon: "🍫",
    categorySlug: "grocery",
    unit: "плитка",
    aliases: ["темный шоколад"],
  },
  {
    name: "Шоколад молочный",
    icon: "🍫",
    categorySlug: "grocery",
    unit: "плитка",
    aliases: ["молочный шоколад"],
  },
  { name: "Мёд", icon: "🍯", categorySlug: "grocery", unit: "г", aliases: [] },
  {
    name: "Варенье",
    icon: "🍯",
    categorySlug: "grocery",
    unit: "банка",
    aliases: [],
  },
  {
    name: "Орехи грецкие",
    icon: "🌰",
    categorySlug: "grocery",
    unit: "г",
    aliases: ["грецкие орехи"],
  },
  {
    name: "Миндаль",
    icon: "🌰",
    categorySlug: "grocery",
    unit: "г",
    aliases: [],
  },
  {
    name: "Кешью",
    icon: "🌰",
    categorySlug: "grocery",
    unit: "г",
    aliases: [],
  },
  { name: "Изюм", icon: "🍇", categorySlug: "grocery", unit: "г", aliases: [] },
  {
    name: "Курага",
    icon: "🍑",
    categorySlug: "grocery",
    unit: "г",
    aliases: [],
  },
  {
    name: "Специи универсальные",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Перец чёрный молотый",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["черный перец", "перец молотый"],
  },
  {
    name: "Паприка молотая",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "уп",
    aliases: ["паприка"],
  },
  {
    name: "Куркума",
    icon: "🧂",
    categorySlug: "grocery",
    unit: "уп",
    aliases: [],
  },

  // --- Заморозка (frozen) ---
  {
    name: "Пельмени",
    icon: "🥟",
    categorySlug: "frozen",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Вареники",
    icon: "🥟",
    categorySlug: "frozen",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Овощи замороженные микс",
    icon: "🧊",
    categorySlug: "frozen",
    unit: "уп",
    aliases: ["овощная смесь замороженная"],
  },
  {
    name: "Брокколи замороженная",
    icon: "🧊",
    categorySlug: "frozen",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Ягоды замороженные микс",
    icon: "🧊",
    categorySlug: "frozen",
    unit: "уп",
    aliases: ["ягодная смесь замороженная"],
  },
  {
    name: "Клубника замороженная",
    icon: "🧊",
    categorySlug: "frozen",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Мороженое",
    icon: "🍦",
    categorySlug: "frozen",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Пицца замороженная",
    icon: "🍕",
    categorySlug: "frozen",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Наггетсы куриные",
    icon: "🍗",
    categorySlug: "frozen",
    unit: "уп",
    aliases: ["наггетсы"],
  },
  {
    name: "Котлеты замороженные",
    icon: "🧊",
    categorySlug: "frozen",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Блинчики замороженные",
    icon: "🥞",
    categorySlug: "frozen",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Кукуруза замороженная",
    icon: "🌽",
    categorySlug: "frozen",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Креветки замороженные",
    icon: "🍤",
    categorySlug: "frozen",
    unit: "кг",
    aliases: [],
  },
  {
    name: "Лёд пищевой",
    icon: "🧊",
    categorySlug: "frozen",
    unit: "уп",
    aliases: ["лед"],
  },

  // --- Хозяйственное (household) ---
  {
    name: "Туалетная бумага",
    icon: "🧻",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Бумажные полотенца",
    icon: "🧻",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Салфетки",
    icon: "🧻",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Влажные салфетки",
    icon: "🧻",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Мыло",
    icon: "🧼",
    categorySlug: "household",
    unit: "шт",
    aliases: [],
  },
  {
    name: "Жидкое мыло",
    icon: "🧴",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Стиральный порошок",
    icon: "🧴",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Кондиционер для белья",
    icon: "🧴",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Средство для мытья посуды",
    icon: "🧴",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Губки для посуды",
    icon: "🧽",
    categorySlug: "household",
    unit: "уп",
    aliases: ["губки"],
  },
  {
    name: "Мусорные пакеты",
    icon: "🗑️",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
  {
    name: "Пищевая плёнка",
    icon: "📦",
    categorySlug: "household",
    unit: "уп",
    aliases: ["стрейч"],
  },
  {
    name: "Фольга пищевая",
    icon: "📦",
    categorySlug: "household",
    unit: "уп",
    aliases: ["фольга"],
  },
  {
    name: "Батарейки",
    icon: "🔋",
    categorySlug: "household",
    unit: "уп",
    aliases: [],
  },
];
